// import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  // facewah
  {
    // _id: uuid(),
    _id: 1,
    title: "Ubtan Face Wash",
    subCategory: "face-wash",
    bestseller: false,
    quantity: "300ml",
    tags: ["Removes Tan, Repairs Sun Damage"],
    price: "259",
    rating: 4.8,
    reviews: 1531,
    categoryName: "face",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },
  {
    // _id: uuid(),
    _id: 2,
    title: "Turmeric and Saffron Face Wash",
    subCategory: "face-wash",
    bestseller: false,
    quantity: "300ml",
    tags: ["Removes Tan, Repairs Sun Damage"],
    price: "259",
    rating: 4.8,
    reviews: 1531,
    categoryName: "face",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },
  {
    // _id: uuid(),
    _id: 3,
    title: "Tea Tree Face Wash",
    subCategory: "face-wash",
    bestseller: false,
    quantity: "300ml",
    tags: ["Controls Acne & Primples", "Removes Excess Oil"],
    price: "259",
    rating: 4.8,
    reviews: 1531,
    categoryName: "face",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },
  {
    // _id: uuid(),
    _id: 4,
    title: "Vitamin C Face Wash",
    subCategory: "face-wash",
    bestseller: false,
    quantity: "100ml",
    tags: ["Brigthens Skin", "Evens Skin Tone", "Makes Skin Glow"],
    price: "259",
    rating: 4.8,
    reviews: 1531,
    categoryName: "face",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },
  {
    // _id: uuid(),
    _id: 5,
    title: "Vitamin C Foaming Face Wash",
    subCategory: "face-wash",
    bestseller: false,
    quantity: "150ml",
    tags: ["Brigthens Skin", "Evens Skin Tone", "Deeply Cleanes"],
    price: "259",
    rating: 4.8,
    reviews: 1531,
    categoryName: "face",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },
  {
    // _id: uuid(),
    _id:6,
    title: "Rice Water Face Wash",
    subCategory: "face-wash",
    bestseller: false,
    quantity: "150ml",
    tags: ["Gently Cleanses Skin", "Hydrates Skin"],
    price: "259",
    rating: 4.8,
    reviews: 1531,
    categoryName: "face",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },
  {
    // _id: uuid(),
    _id:7,
    title: "Charcoal Face Wash",
    subCategory: "face-wash",
    bestseller: false,
    quantity: "150ml",
    tags: ["Pollution Defense Formula", "Controls Excess Oil"],
    price: "259",
    rating: 4.8,
    reviews: 1531,
    categoryName: "face",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },

  // facemask
  {
    _id: 8,
    title: "Vitamin C Daily Glow Face Mask ",
    bestseller: false,
    quantity: "100 g",
    subCategory: "face-mask",
    tags: "Removes Tan, Repairs Sun Damage",
    price: "499",
    rating: 4.8,
    reviews: 1531,
    categoryName: "face",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 9,
    title: "Charcoal Face Mask ",
    bestseller: false,
    subCategory: "face-mask",
    quantity: "100 g",
    tags: "Removes Tan, Repairs Sun Damage",
    price: "599",
    rating: 4.8,
    reviews: 31,
    categoryName: "face",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 10,
    title: "C3 Face Mask ",
    bestseller: true,
    subCategory: "face-mask",
    quantity: "100 g",
    tags: ["Makes Skin Glow", "Reduces Acne & Pimples"],
    price: "599",
    rating: 4.8,
    reviews: 31,
    categoryName: "face",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },

  // face cream
  {
    _id: 11,
    title: "Winter Face Cream ",
    bestseller: true,
    quantity: "100 g",
    tags: ["Makes Skin Glow", "Reduces Acne & Pimples"],
    price: "599",
    rating: 4.8,
    reviews: 31,
    categoryName: "face",
    subCategory: "face-cream",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },

  // completed Face

  // Beauty
  {
    _id: 12,
    title: "Feather Light Red-Velvet Lipstick",
    bestseller: false,
    newLaunch: "true",
    quantity: "3.5 ml",
    tags: ["16-Hour Long Stay", "Made Safe Certified"],
    price: "499",
    rating: 5,
    reviews: 11,
    categoryName: "beauty",
    subCategory: "lipstick",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 13,
    title: "Feather Light Pink Lipstick",
    bestseller: true,
    newLaunch: false,
    quantity: "3.5 ml",
    tags: ["16-Hour Long Stay", "Made Safe Certified"],
    price: "599",
    rating: 4.9,
    reviews: 113,
    categoryName: "beauty",
    subCategory: "lipstick",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 14,
    title: "Feather Light Nude Brown Lipstick",
    bestseller: false,
    newLaunch: "true",
    quantity: "3.5 ml",
    tags: ["16-Hour Long Stay", "Made Safe Certified"],
    price: "699",
    rating: 5,
    reviews: 11,
    categoryName: "beauty",
    subCategory: "lipstick",
    image:
      "https://images.mamaearth.in/catalog/product/u/b/ubtan-face-wash_1_1_1.jpg?fit=contain&width=400&height=400",
  },
  // oil
  {
    _id: 15,
    title: "Henna Hair Oil with Henna",
    bestseller: false,
    newLaunch: "true",
    quantity: "100 ml",
    tags: ["Nourishes Hair", "Prevents Premature Greying"],
    price: "519",
    rating: 4.6,
    reviews: 113,
    categoryName: "beauty",
    subCategory: "hair-oil",
    image:
      "https://images.mamaearth.in/catalog/product/h/e/henna-oil-2.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 16,
    title: "Onion Hair Oil",
    bestseller: false,
    newLaunch: "true",
    quantity: "100 ml",
    tags: ["Nourishes Hair", "Prevents Premature Greying"],
    price: "519",
    rating: 4.6,
    reviews: 113,
    categoryName: "beauty",
    subCategory: "hair-oil",
    image:
      "https://images.mamaearth.in/catalog/product/_/o/_onion-oil-150ml_.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 17,
    title: "Hair Oil Booster- Almond",
    bestseller: false,
    newLaunch: "true",
    quantity: "30 ml",
    tags: ["Nourishes Hair", "Boosts Growth", "Non-Sticky"],
    price: "349",
    rating: 4.4,
    reviews: 63,
    categoryName: "beauty",
    subCategory: "hair-oil",
    image:
      "https://images.mamaearth.in/catalog/product/a/l/almond-1_1.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 18,
    title: "Hair Oil Booster- Almond",
    bestseller: false,
    newLaunch: "true",
    quantity: "30 ml",
    tags: ["Nourishes Hair", "Boosts Growth", "Non-Sticky"],
    price: "349",
    rating: 4.4,
    reviews: 63,
    categoryName: "beauty",
    subCategory: "hair-oil",
    image:
      "https://images.mamaearth.in/catalog/product/a/l/almond-1_1.jpg?fit=contain&width=400&height=400",
  },

  // Make-Up
  {
    _id: 19,
    title: "Charcoal Black Long Stay Kajl Pencil",
    bestseller: true,
    newLaunch: false,
    quantity: "Pack of 2",
    tags: ["11-Hour Long Stay", "Smudge Proof"],
    price: "499",
    rating: 4.4,
    reviews: 63,
    categoryName: "makeup",
    subCategory: "kajal",
    image:
      "https://images.mamaearth.in/catalog/product/k/o/kohl_listing_image_white_bg.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 20,
    title: "Soothing Waterproof Eyelines with Almond",
    bestseller: true,
    newLaunch: false,
    quantity: "Pack of 1",
    tags: ["Waterproof Formula", "10 Second Drying Time"],
    price: "499",
    rating: 4.4,
    reviews: 63,
    categoryName: "makeup",
    subCategory: "kajal",
    image:
      "https://images.mamaearth.in/catalog/product/p/r/product_swatch_2.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 21,
    title: "Soothing Waterproof Eyelines",
    bestseller: true,
    newLaunch: false,
    quantity: "Pack of 2",
    tags: ["Waterproof Formula", "10 Second Drying Time"],
    price: "799",
    rating: 4.4,
    reviews: 63,
    categoryName: "makeup",
    subCategory: "kajal",
    image:
      "https://images.mamaearth.in/catalog/product/p/r/product_swatch_2.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 22,
    title: "Charcoal Black Long Stay Kajal",
    bestseller: true,
    newLaunch: false,
    quantity: "0.35 g",
    tags: ["Waterproof Formula", "10 Second Drying Time"],
    price: "580",
    rating: 4.4,
    reviews: 63,
    categoryName: "makeup",
    image:
      "https://images.mamaearth.in/catalog/product/k/a/kajal_pack_of_2.jpg?fit=contain&width=400&height=400",
  },
  //  complete makeup

  // Baby
  {
    _id: 23,
    title: "Charcoal Black Long Stay Kajal",
    bestseller: true,
    newLaunch: false,
    quantity: "0.35 g",
    tags: ["Waterproof Formula", "10 Second Drying Time"],
    price: "580",
    rating: 4.4,
    reviews: 63,
    categoryName: "baby",
    image:
      "https://images.mamaearth.in/catalog/product/k/a/kajal_pack_of_2.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 24,
    title: "Charcoal Black Long Stay Kajal",
    bestseller: true,
    newLaunch: false,
    quantity: "0.35 g",
    tags: ["Waterproof Formula", "10 Second Drying Time"],
    price: "580",
    rating: 4.4,
    reviews: 63,
    categoryName: "baby",
    image:
      "https://images.mamaearth.in/catalog/product/k/a/kajal_pack_of_2.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 25,
    title: "Charcoal Black Long Stay Kajal",
    bestseller: true,
    newLaunch: false,
    quantity: "0.35 g",
    tags: ["Waterproof Formula", "10 Second Drying Time"],
    price: "580",
    rating: 4.4,
    reviews: 63,
    categoryName: "baby",
    image:
      "https://images.mamaearth.in/catalog/product/k/a/kajal_pack_of_2.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 26,
    title: "Charcoal Black Long Stay Kajal",
    bestseller: true,
    newLaunch: false,
    quantity: "0.35 g",
    tags: ["Waterproof Formula", "10 Second Drying Time"],
    price: "580",
    rating: 4.4,
    reviews: 63,
    categoryName: "baby",
    image:
      "https://images.mamaearth.in/catalog/product/k/a/kajal_pack_of_2.jpg?fit=contain&width=400&height=400",
  },

  // plant-goodness
  {
    _id: 27,
    title: "Charcoal Black Long Stay Kajal",
    bestseller: true,
    newLaunch: false,
    quantity: "0.35 g",
    tags: ["Waterproof Formula", "10 Second Drying Time"],
    price: "580",
    rating: 4.4,
    reviews: 63,
    categoryName: "plant-goodness",
    image:
      "https://images.mamaearth.in/catalog/product/k/a/kajal_pack_of_2.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 28,
    title: "Charcoal Black Long Stay Kajal",
    bestseller: true,
    newLaunch: false,
    quantity: "0.35 g",
    tags: ["Waterproof Formula", "10 Second Drying Time"],
    price: "580",
    rating: 4.4,
    reviews: 63,
    categoryName: "plant-goodness",
    image:
      "https://images.mamaearth.in/catalog/product/k/a/kajal_pack_of_2.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 29,
    title: "Charcoal Black Long Stay Kajal",
    bestseller: true,
    newLaunch: false,
    quantity: "0.35 g",
    tags: ["Waterproof Formula", "10 Second Drying Time"],
    price: "580",
    rating: 4.4,
    reviews: 63,
    categoryName: "plant-goodness",
    image:
      "https://images.mamaearth.in/catalog/product/k/a/kajal_pack_of_2.jpg?fit=contain&width=400&height=400",
  },
  {
    _id: 30,
    title: "Charcoal Black Long Stay Kajal",
    bestseller: true,
    newLaunch: false,
    quantity: "0.35 g",
    tags: ["Waterproof Formula", "10 Second Drying Time"],
    price: "580",
    rating: 4.4,
    reviews: 63,
    categoryName: "plant-goodness",
    image:
      "https://images.mamaearth.in/catalog/product/k/a/kajal_pack_of_2.jpg?fit=contain&width=400&height=400",
  },
];
